# Generated by Django 5.0.6 on 2024-06-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_eligible_date',
            field=models.DateField(default=-2016),
            preserve_default=False,
        ),
    ]
