# Generated by Django 5.0.6 on 2024-06-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_service_service_eligible_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_eligible_date',
        ),
        migrations.AddField(
            model_name='service',
            name='service_eligible_status',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
