# Generated by Django 5.0.6 on 2024-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_service_service_eligible_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_eligible_status',
            field=models.BooleanField(default=True),
        ),
    ]
