# Generated by Django 5.0.6 on 2024-06-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedata', '0002_alter_store_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
