# Generated by Django 5.0.6 on 2024-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedata', '0003_alter_store_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='password',
            field=models.CharField(max_length=51),
        ),
    ]
